// Starward
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const UPDATE_STARWARD_STATE = 'UPDATE_STARWARD_STATE';
export const UPDATE_STARWARD_STATE_SUCCESS = 'UPDATE_STARWARD_STATE_SUCCESS';
export const UPDATE_STARWARD_STATE_FAILURE = 'UPDATE_STARWARD_STATE_FAILURE';
export const RESET_404 = 'RESET_404';

// Gravity Forms
export const GET_FORM = 'GET_FORM';
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS';
export const GET_FORM_FAILURE = 'GET_FORM_FAILURE';
export const UPDATE_FORM = 'UPDATE_FORM';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE';

// WooCommerce Cart
export const GET_CART = 'GET_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

// GTM Actions
export const GTM_TRACK_PAGE_CHANGE = 'GTM_TRACK_PAGE_CHANGE';
