// Starward
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const UPDATE_STARWARD_STATE = 'UPDATE_STARWARD_STATE';
export const UPDATE_STARWARD_STATE_SUCCESS = 'UPDATE_STARWARD_STATE_SUCCESS';
export const UPDATE_STARWARD_STATE_FAILURE = 'UPDATE_STARWARD_STATE_FAILURE';
export const RESET_404 = 'RESET_404';

// Gravity Forms
export const GET_FORM = 'GET_FORM';
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS';
export const GET_FORM_FAILURE = 'GET_FORM_FAILURE';
export const UPDATE_FORM = 'UPDATE_FORM';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE';
